### ISSUE TITLE
facing issues on build

### ISSUE THREAD

**Issue by snps-owaine** [benbaker76/linux-acs-override#4]
I'm running ubuntu 22.04 and currently on 5.15.0

I've cloned the repo and run ./build_debian.sh

I left defaults for 6.3 and it failed.

Attempted the fix of removing the certificate and building again with failure at:

LD [M]  fs/btrfs/btrfs.o
make[5]: *** [Makefile:2025: .] Error 2
make[4]: *** [Makefile:357: __build_one_by_one] Error 2
make[3]: *** [debian/rules:8: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[2]: *** [scripts/Makefile.package:114: bindeb-pkg] Error 2
make[1]: *** [Makefile:1656: bindeb-pkg] Error 2
make: *** [Makefile:357: __build_one_by_one] Error 2

Attempted build of 6.5 and got an error at:

LD [M]  fs/ocfs2/ocfs2.o
make[6]: *** [Makefile:2032: .] Error 2
make[5]: *** [Makefile:359: __build_one_by_one] Error 2
make[4]: *** [debian/rules:10: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[3]: *** [scripts/Makefile.package:139: bindeb-pkg] Error 2
make[2]: *** [Makefile:1659: bindeb-pkg] Error 2
make[1]: *** [/root/linux-acs-override/linux-6.5/Makefile:359: __build_one_by_one] Error 2
make: *** [Makefile:234: __sub-make] Error 2

**Comment by snps-owaine** [comment]
update to the last:

I attempted updating to 23.04 to see if I could build still fail on same thing.

updated to the latest gcc and g++ in case it was a compiler issue and still fail:

  LD [M]  fs/ocfs2/ocfs2.o
make[5]: *** [Makefile:2025: .] Error 2
make[4]: *** [Makefile:357: __build_one_by_one] Error 2
make[3]: *** [debian/rules:8: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[2]: *** [scripts/Makefile.package:114: bindeb-pkg] Error 2
make[1]: *** [Makefile:1656: bindeb-pkg] Error 2
make: *** [Makefile:357: __build_one_by_one] Error 2

**Comment by benbaker76** [comment]
Try setting the make line to use one job (`-j 1`). It will take a long time but you should get the real error.

**Comment by flotwig** [comment]
@benbaker76 I tried to comment out that line but the `make olddefconfig [...]` command from `build-debian.sh` overwrites my change to `.config`. If I just run `make [...]` using the same options, I get prompted to fill out `CONFIG_SYSTEM_TRUSTED_KEYS`.

Running with `-j 1` the error is clear. Luckily it happens early enough in the build process that I didn't have to wait long:

```
  CC      init/version-timestamp.o
BTF: .tmp_vmlinux.btf: pahole (pahole) is not available
Failed to generate BTF for vmlinux
Try to disable CONFIG_DEBUG_INFO_BTF
make[6]: *** [scripts/Makefile.vmlinux:35: vmlinux] Error 1
make[5]: *** [Makefile:1249: vmlinux] Error 2
make[4]: *** [Makefile:357: __build_one_by_one] Error 2
make[3]: *** [debian/rules:8: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[2]: *** [scripts/Makefile.package:114: bindeb-pkg] Error 2
make[1]: *** [Makefile:1656: bindeb-pkg] Error 2
make: *** [Makefile:357: __build_one_by_one] Error 2
```

https://stackoverflow.com/a/61758176/3474615 recommends installing `dwarves`. After running `apt install dwarves` I am able to successfully run `build-debian.sh`.

I opened a PR to fix this issue by adding `dwarves` to `build-debian.sh`: #5
